version: "3"
services:
  postgresql:
    image: postgres:14.3-alpine
    container_name: jwt_api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=jwt_api
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.16
    container_name: redis-jwt_api
    ports:
      - "6379:6379"

